# Generated by Django 5.2.4 on 2025-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaff',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
