# Generated by Django 5.2.4 on 2025-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_hospitalstaff_is_occupied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='available_ambulances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='total_ambulances',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
