# Generated by Django 5.2.4 on 2025-07-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_hospital_available_ambulances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='ambulance_dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='ambulance_required',
            field=models.BooleanField(default=False),
        ),
    ]
