# Generated by Django 5.2.4 on 2025-07-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergencyrequest_ambulance_dispatched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emergency.hospitalstaff'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
