# Generated by Django 5.2.4 on 2025-07-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_emergencyrequest_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
    ]
